 export default function TagCloud(){
    return (
    <div className="tag-cloud text-gray-400">
    <div id="tag_cloud_header"><p><a className="tag_heading_selected" title="show a cloud of your most-used tags" href="?mode=cloud">top tags  &nbsp;&nbsp; 
 &nbsp;&nbsp;</a><a href="?mode=list&amp;floor=1" title="show a list of all your tags">all tags</a> <nbsp />
 ‧ <a href="?mode=list&amp;floor=2" title="show tags with at least 2 bookmarks">2</a>  ‧ <a href="?mode=list&amp;floor=5" title="show tags with at least 5 bookmarks">5</a>  ‧ <a href="?mode=list&amp;floor=10" title="show tags with at least 10 bookmarks">10</a>  ‧ <a href="?mode=list&amp;floor=20" title="show tags with at least 20 bookmarks">20</a> ‧ <a href="/u:paan/tags/">manage</a></p></div>
 <div className="text-gray-300">
 <a href="/u:paan/t:algorithm/" className="14.0.7 tag">algorithm</a> <nbsp /> 
<a href="/u:paan/t:android/" className="15.1 tag">android</a> <nbsp /> 
<a href="/u:paan/t:android-app/" className="16.1 tag">android-app</a> <nbsp /> 
<a href="/u:paan/t:ansi-art/" className="14.0.7 tag">ansi-art</a> <nbsp /> 
<a href="/u:paan/t:arcanum/" className="14.0.6 tag">arcanum</a> <nbsp /> 
<a href="/u:paan/t:art/" className="14.0.6 tag">art</a> <nbsp /> 
<a href="/u:paan/t:article/" className="14.0.8 tag">article</a> <nbsp /> 
<a href="/u:paan/t:articles/" className="14.0.7 tag">articles</a> <nbsp /> 
<a href="/u:paan/t:ascii-art/" className="14.0.7 tag">ascii-art</a> <nbsp /> 
<a href="/u:paan/t:audible/" className="14.0.7 tag">audible</a> <nbsp /> 
<a href="/u:paan/t:audio/" className="14.0.6 tag">audio</a> <nbsp /> 
<a href="/u:paan/t:backing-tracks/" className="14.0.6 tag">backing-tracks</a> <nbsp /> 
<a href="/u:paan/t:backup/" className="14.0.6 tag">backup</a> <nbsp /> 
<a href="/u:paan/t:baldurs-gate/" className="14.0.6 tag">baldurs-gate</a> <nbsp /> 
<a href="/u:paan/t:bazaar/" className="14.0.4 tag">bazaar</a> <nbsp /> 
<a href="/u:paan/t:bfme/" className="14.0.4 tag">bfme</a> <nbsp /> 
<a href="/u:paan/t:blog/" className="14.0.7 tag">blog</a> <nbsp /> 
<a href="/u:paan/t:bloodbowl/" className="14.0.4 tag">bloodbowl</a> <nbsp /> 
<a href="/u:paan/t:boardgames/" className="19.1 tag">boardgames</a> <nbsp /> 
<a href="/u:paan/t:bookmarking/" className="14.0.7 tag">bookmarking</a> <nbsp /> 
<a href="/u:paan/t:browser-game/" className="16.1 tag">browser-game</a> <nbsp /> 
<a href="/u:paan/t:c/" className="14.0.4 tag">c</a> <nbsp /> 
<a href="/u:paan/t:C%2523/" className="15.1 tag">C#</a> <nbsp /> 
<a href="/u:paan/t:campaign-cartographer/" className="14.0.4 tag">campaign-cartographer</a> <nbsp /> 
<a href="/u:paan/t:ccg/" className="14.0.4 tag">ccg</a> <nbsp /> 
<a href="/u:paan/t:chess/" className="14.0.6 tag">chess</a> <nbsp /> 
<a href="/u:paan/t:chrome-extensions/" className="14.0.9 tag">chrome-extensions</a> <nbsp /> 
<a href="/u:paan/t:cloud-storage/" className="14.0.4 tag">cloud-storage</a> <nbsp /> 
<a href="/u:paan/t:code-hosting/" className="14.0.4 tag">code-hosting</a> <nbsp /> 
<a href="/u:paan/t:codebase/" className="14.0.4 tag">codebase</a> <nbsp /> 
<a href="/u:paan/t:coh/" className="14.0.6 tag">coh</a> <nbsp /> 
<a href="/u:paan/t:comic/" className="14.0.4 tag">comic</a> <nbsp /> 
<a href="/u:paan/t:connection-string/" className="14.0.4 tag">connection-string</a> <nbsp /> 
<a href="/u:paan/t:ConQUEST/" className="14.0.6 tag">ConQUEST</a> <nbsp /> 
<a href="/u:paan/t:cryptography/" className="14.0.4 tag">cryptography</a> <nbsp /> 
<a href="/u:paan/t:cube-drafting/" className="14.0.7 tag">cube-drafting</a> <nbsp /> 
<a href="/u:paan/t:culdcept/" className="14.0.6 tag">culdcept</a> <nbsp /> 
<a href="/u:paan/t:cyoa/" className="14.0.4 tag">cyoa</a> <nbsp /> 
<a href="/u:paan/t:D%2526D3e/" className="14.0.4 tag">D&amp;D3e</a> <nbsp /> 
<a href="/u:paan/t:DDO/" className="14.0.9 tag">DDO</a> <nbsp /> 
<a href="/u:paan/t:deals/" className="14.0.4 tag">deals</a> <nbsp /> 
<a href="/u:paan/t:debugger/" className="14.0.7 tag">debugger</a> <nbsp /> 
<a href="/u:paan/t:decklist/" className="14.0.9 tag">decklist</a> <nbsp /> 
<a href="/u:paan/t:design/" className="14.0.9 tag">design</a> <nbsp /> 
<a href="/u:paan/t:design-patterns/" className="14.0.7 tag">design-patterns</a> <nbsp /> 
<a href="/u:paan/t:desktop/" className="14.0.4 tag">desktop</a> <nbsp /> 
<a href="/u:paan/t:development/" className="18.1 tag">development</a> <nbsp /> 
<a href="/u:paan/t:diagram-editor/" className="14.0.4 tag">diagram-editor</a> <nbsp /> 
<a href="/u:paan/t:dice-roller/" className="14.0.6 tag">dice-roller</a> <nbsp /> 
<a href="/u:paan/t:dnd/" className="14.0.7 tag">dnd</a> <nbsp /> 
<a href="/u:paan/t:drafting/" className="14.0.4 tag">drafting</a> <nbsp /> 
<a href="/u:paan/t:dragonage/" className="14.0.4 tag">dragonage</a> <nbsp /> 
<a href="/u:paan/t:drm/" className="14.0.4 tag">drm</a> <nbsp /> 
<a href="/u:paan/t:duel2/" className="14.0.7 tag">duel2</a> <nbsp /> 
<a href="/u:paan/t:dues-ex/" className="14.0.4 tag">dues-ex</a> <nbsp /> 
<a href="/u:paan/t:dungrove/" className="14.0.7 tag">dungrove</a> <nbsp /> 
<a href="/u:paan/t:edh/" className="14.0.8 tag">edh</a> <nbsp /> 
<a href="/u:paan/t:ELO/" className="14.0.4 tag">ELO</a> <nbsp /> 
<a href="/u:paan/t:encryption/" className="14.0.6 tag">encryption</a> <nbsp /> 
<a href="/u:paan/t:eq/" className="14.0.6 tag">eq</a> <nbsp /> 
<a href="/u:paan/t:example/" className="14.0.4 tag">example</a> <nbsp /> 
<a href="/u:paan/t:f2p/" className="14.0.6 tag">f2p</a> <nbsp /> 
<a href="/u:paan/t:file-sharing/" className="14.0.4 tag">file-sharing</a> <nbsp /> 
<a href="/u:paan/t:finance/" className="14.0.4 tag">finance</a> <nbsp /> 
<a href="/u:paan/t:flash/" className="14.0.7 tag">flash</a> <nbsp /> 
<a href="/u:paan/t:flash-games/" className="14.0.6 tag">flash-games</a> <nbsp /> 
<a href="/u:paan/t:flutter/" className="14.0.4 tag">flutter</a> <nbsp /> 
<a href="/u:paan/t:game/" className="17.1 tag">game</a> <nbsp /> 
<a href="/u:paan/t:game-design/" className="14.0.7 tag">game-design</a> <nbsp /> 
<a href="/u:paan/t:game-development/" className="14.0.7 tag">game-development</a> <nbsp /> 
<a href="/u:paan/t:games/" className="14.0.9 tag">games</a> <nbsp /> 
<a href="/u:paan/t:gaming/" className="14.0.8 tag">gaming</a> <nbsp /> 
<a href="/u:paan/t:git/" className="14.0.7 tag">git</a> <nbsp /> 
<a href="/u:paan/t:goldbox/" className="14.0.4 tag">goldbox</a> <nbsp /> 
<a href="/u:paan/t:gpg/" className="14.0.4 tag">gpg</a> <nbsp /> 
<a href="/u:paan/t:gps/" className="14.0.8 tag">gps</a> <nbsp /> 
<a href="/u:paan/t:hdd/" className="14.0.4 tag">hdd</a> <nbsp /> 
<a href="/u:paan/t:headphones/" className="14.0.4 tag">headphones</a> <nbsp /> 
<a href="/u:paan/t:hmm/" className="14.0.4 tag">hmm</a> <nbsp /> 
<a href="/u:paan/t:home-screen/" className="14.0.4 tag">home-screen</a> <nbsp /> 
<a href="/u:paan/t:hosting/" className="14.0.7 tag">hosting</a> <nbsp /> 
<a href="/u:paan/t:hotspot/" className="14.0.4 tag">hotspot</a> <nbsp /> 
<a href="/u:paan/t:ide/" className="14.0.8 tag">ide</a> <nbsp /> 
<a href="/u:paan/t:if/" className="14.0.4 tag">if</a> <nbsp /> 
<a href="/u:paan/t:image/" className="14.0.4 tag">image</a> <nbsp /> 
<a href="/u:paan/t:indie-game/" className="14.0.9 tag">indie-game</a> <nbsp /> 
<a href="/u:paan/t:infinity-engine/" className="14.0.4 tag">infinity-engine</a> <nbsp /> 
<a href="/u:paan/t:interactive-novel/" className="14.0.8 tag">interactive-novel</a> <nbsp /> 
<a href="/u:paan/t:issue-tracking/" className="14.0.9 tag">issue-tracking</a> <nbsp /> 
<a href="/u:paan/t:kickstarter/" className="14.0.4 tag">kickstarter</a> <nbsp /> 
<a href="/u:paan/t:links/" className="14.0.4 tag">links</a> <nbsp /> 
<a href="/u:paan/t:linq/" className="14.0.4 tag">linq</a> <nbsp /> 
<a href="/u:paan/t:lotro/" className="14.0.4 tag">lotro</a> <nbsp /> 
<a href="/u:paan/t:map/" className="14.0.6 tag">map</a> <nbsp /> 
<a href="/u:paan/t:math/" className="14.0.6 tag">math</a> <nbsp /> 
<a href="/u:paan/t:maybank2u-research/" className="14.0.9 tag">maybank2u-research</a> <nbsp /> 
<a href="/u:paan/t:mmo/" className="14.0.8 tag">mmo</a> <nbsp /> 
<a href="/u:paan/t:mod/" className="14.0.8 tag">mod</a> <nbsp /> 
<a href="/u:paan/t:mono-green/" className="14.0.7 tag">mono-green</a> <nbsp /> 
<a href="/u:paan/t:Morrowind/" className="14.0.9 tag">Morrowind</a> <nbsp /> 
<a href="/u:paan/t:morrrowind/" className="14.0.4 tag">morrrowind</a> <nbsp /> 
<a href="/u:paan/t:movies/" className="14.0.4 tag">movies</a> <nbsp /> 
<a href="/u:paan/t:mp3/" className="14.0.7 tag">mp3</a> <nbsp /> 
<a href="/u:paan/t:mp3player/" className="14.0.7 tag">mp3player</a> <nbsp /> 
<a href="/u:paan/t:mssp/" className="14.0.4 tag">mssp</a> <nbsp /> 
<a href="/u:paan/t:mtg/" className="17.1 tag">mtg</a> <nbsp /> 
<a href="/u:paan/t:mud/" className="19.1 tag">mud</a> <nbsp /> 
<a href="/u:paan/t:mud-research/" className="16.1 tag">mud-research</a> <nbsp /> 
<a href="/u:paan/t:mud-server/" className="14.0.9 tag">mud-server</a> <nbsp /> 
<a href="/u:paan/t:music/" className="14.0.7 tag">music</a> <nbsp /> 
<a href="/u:paan/t:mxp/" className="14.0.6 tag">mxp</a> <nbsp /> 
<a href="/u:paan/t:nakedmud/" className="14.0.4 tag">nakedmud</a> <nbsp /> 
<a href="/u:paan/t:nds/" className="14.0.7 tag">nds</a> <nbsp /> 
<a href="/u:paan/t:nes/" className="14.0.4 tag">nes</a> <nbsp /> 
<a href="/u:paan/t:network-monitor/" className="14.0.4 tag">network-monitor</a> <nbsp /> 
<a href="/u:paan/t:newsgroup/" className="14.0.4 tag">newsgroup</a> <nbsp /> 
<a href="/u:paan/t:not-enough-space/" className="14.0.4 tag">not-enough-space</a> <nbsp /> 
<a href="/u:paan/t:notes-taking/" className="14.1 tag">notes-taking</a> <nbsp /> 
<a href="/u:paan/t:nova-guild/" className="14.0.4 tag">nova-guild</a> <nbsp /> 
<a href="/u:paan/t:online-storage/" className="14.0.9 tag">online-storage</a> <nbsp /> 
<a href="/u:paan/t:outliner/" className="14.1 tag">outliner</a> <nbsp /> 
<a href="/u:paan/t:paid-apps/" className="14.0.7 tag">paid-apps</a> <nbsp /> 
<a href="/u:paan/t:panzer-general/" className="14.0.7 tag">panzer-general</a> <nbsp /> 
<a href="/u:paan/t:password/" className="14.0.4 tag">password</a> <nbsp /> 
<a href="/u:paan/t:patch/" className="14.0.6 tag">patch</a> <nbsp /> 
<a href="/u:paan/t:pbm/" className="14.0.4 tag">pbm</a> <nbsp /> 
<a href="/u:paan/t:peoples-general/" className="14.0.7 tag">peoples-general</a> <nbsp /> 
<a href="/u:paan/t:php/" className="14.0.9 tag">php</a> <nbsp /> 
<a href="/u:paan/t:pinboard/" className="14.0.6 tag">pinboard</a> <nbsp /> 
<a href="/u:paan/t:pixelart/" className="14.0.9 tag">pixelart</a> <nbsp /> 
<a href="/u:paan/t:podcast/" className="14.0.8 tag">podcast</a> <nbsp /> 
<a href="/u:paan/t:print-and-play/" className="18.1 tag">print-and-play</a> <nbsp /> 
<a href="/u:paan/t:project-hosting/" className="17.1 tag">project-hosting</a> <nbsp /> 
<a href="/u:paan/t:project-management/" className="14.0.4 tag">project-management</a> <nbsp /> 
<a href="/u:paan/t:publishing/" className="14.0.4 tag">publishing</a> <nbsp /> 
<a href="/u:paan/t:python/" className="14.0.4 tag">python</a> <nbsp /> 
<a href="/u:paan/t:random/" className="14.0.4 tag">random</a> <nbsp /> 
<a href="/u:paan/t:remake/" className="14.0.4 tag">remake</a> <nbsp /> 
<a href="/u:paan/t:rest/" className="14.0.6 tag">rest</a> <nbsp /> 
<a href="/u:paan/t:rng/" className="14.0.7 tag">rng</a> <nbsp /> 
<a href="/u:paan/t:roguelike/" className="14.0.8 tag">roguelike</a> <nbsp /> 
<a href="/u:paan/t:rom/" className="14.0.8 tag">rom</a> <nbsp /> 
<a href="/u:paan/t:roms/" className="14.0.7 tag">roms</a> <nbsp /> 
<a href="/u:paan/t:round-robin/" className="14.0.9 tag">round-robin</a> <nbsp /> 
<a href="/u:paan/t:rpg/" className="14.0.9 tag">rpg</a> <nbsp /> 
<a href="/u:paan/t:rss/" className="14.0.6 tag">rss</a> <nbsp /> 
<a href="/u:paan/t:rules/" className="14.0.4 tag">rules</a> <nbsp /> 
<a href="/u:paan/t:runesofmagic/" className="14.0.4 tag">runesofmagic</a> <nbsp /> 
<a href="/u:paan/t:running/" className="14.0.6 tag">running</a> <nbsp /> 
<a href="/u:paan/t:security/" className="14.0.6 tag">security</a> <nbsp /> 
<a href="/u:paan/t:self-hosted/" className="14.0.7 tag">self-hosted</a> <nbsp /> 
<a href="/u:paan/t:serialization/" className="14.0.8 tag">serialization</a> <nbsp /> 
<a href="/u:paan/t:shmup/" className="14.0.6 tag">shmup</a> <nbsp /> 
<a href="/u:paan/t:shuffling/" className="14.0.4 tag">shuffling</a> <nbsp /> 
<a href="/u:paan/t:simhq/" className="14.0.7 tag">simhq</a> <nbsp /> 
<a href="/u:paan/t:social-tool/" className="14.0.6 tag">social-tool</a> <nbsp /> 
<a href="/u:paan/t:sound/" className="14.0.7 tag">sound</a> <nbsp /> 
<a href="/u:paan/t:sqlce/" className="14.0.7 tag">sqlce</a> <nbsp /> 
<a href="/u:paan/t:sqlite/" className="14.0.4 tag">sqlite</a> <nbsp /> 
<a href="/u:paan/t:store/" className="14.0.4 tag">store</a> <nbsp /> 
<a href="/u:paan/t:streams/" className="14.0.4 tag">streams</a> <nbsp /> 
<a href="/u:paan/t:svn/" className="14.0.4 tag">svn</a> <nbsp /> 
<a href="/u:paan/t:svn-hosting/" className="14.1 tag">svn-hosting</a> <nbsp /> 
<a href="/u:paan/t:tasker/" className="14.0.4 tag">tasker</a> <nbsp /> 
<a href="/u:paan/t:tcg/" className="14.0.9 tag">tcg</a> <nbsp /> 
<a href="/u:paan/t:tech/" className="14.0.4 tag">tech</a> <nbsp /> 
<a href="/u:paan/t:telnet/" className="14.0.4 tag">telnet</a> <nbsp /> 
<a href="/u:paan/t:test/" className="14.0.4 tag">test</a> <nbsp /> 
<a href="/u:paan/t:text-editor/" className="14.0.8 tag">text-editor</a> <nbsp /> 
<a href="/u:paan/t:titanquest/" className="14.0.8 tag">titanquest</a> <nbsp /> 
<a href="/u:paan/t:todo/" className="17.1 tag">todo</a> <nbsp /> 
<a href="/u:paan/t:touch-cruise/" className="14.0.7 tag">touch-cruise</a> <nbsp /> 
<a href="/u:paan/t:tutorial/" className="14.0.6 tag">tutorial</a> <nbsp /> 
<a href="/u:paan/t:twitter/" className="14.0.6 tag">twitter</a> <nbsp /> 
<a href="/u:paan/t:twitter-client/" className="14.0.4 tag">twitter-client</a> <nbsp /> 
<a href="/u:paan/t:typing/" className="14.0.4 tag">typing</a> <nbsp /> 
<a href="/u:paan/t:uml-editor/" className="14.0.4 tag">uml-editor</a> <nbsp /> 
<a href="/u:paan/t:url-shorteners/" className="14.0.4 tag">url-shorteners</a> <nbsp /> 
<a href="/u:paan/t:useful-software/" className="21.1 tag">useful-software</a> <nbsp /> 
<a href="/u:paan/t:usenet/" className="14.0.4 tag">usenet</a> <nbsp /> 
<a href="/u:paan/t:virtual-tabletop/" className="14.0.8 tag">virtual-tabletop</a> <nbsp /> 
<a href="/u:paan/t:vps-hosting/" className="14.0.7 tag">vps-hosting</a> <nbsp /> 
<a href="/u:paan/t:wargame/" className="14.0.9 tag">wargame</a> <nbsp /> 
<a href="/u:paan/t:web20/" className="14.0.4 tag">web20</a> <nbsp /> 
<a href="/u:paan/t:webapps/" className="14.0.9 tag">webapps</a> <nbsp /> 
<a href="/u:paan/t:Werewolf/" className="14.0.8 tag">Werewolf</a> <nbsp /> 
<a href="/u:paan/t:wheelmud/" className="14.0.4 tag">wheelmud</a> <nbsp /> 
<a href="/u:paan/t:widgets/" className="14.0.4 tag">widgets</a> <nbsp /> 
<a href="/u:paan/t:wifi/" className="14.0.4 tag">wifi</a> <nbsp /> 
<a href="/u:paan/t:windows/" className="14.0.4 tag">windows</a> <nbsp /> 
<a href="/u:paan/t:wordpress/" className="14.0.4 tag">wordpress</a> <nbsp /> 
<a href="/u:paan/t:wp-theme/" className="17.1 tag">wp-theme</a> <nbsp /> 
<a href="/u:paan/t:writing/" className="14.0.8 tag">writing</a> <nbsp /> 
</div>

</div>
)
}