name: Linkstash
services:  
  linkstash-backend:
    image: paan1981/linkstash-backend-nightly:nightly-20240818-03
    environment:
      DB_HOST: ${DB_HOST:-linkstash-db}
      DB_PORT: ${DB_PORT:-3306}
      DB_USER: ${DB_USER:-linkstash}
      DB_PASSWORD: ${DB_PASSWORD:-password}
      DB_NAME: ${DB_NAME:-linkstash-backend}
      PORT: 3030
    ports:
      - ${BACKEND_PORT:-3030}:3030 
    volumes:
      - ./config:/home/node/app/config
      - ./archive:/home/node/app/public/archive
    depends_on:
      linkstash-db:
        condition: service_healthy
  linkstash-db:
    image: linuxserver/mariadb:10.11.8
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=100 
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD:-password}
      - MYSQL_DATABASE=${DB_NAME:-linkstash-backend}
      - MYSQL_USER=${DB_USER:-linkstash}
      - MYSQL_PASSWORD=${DB_PASSWORD:-password}
    volumes:
      - linkstash-data:/config
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 30
  linkstash-frontend:
    image: paan1981/linkstash-frontend-nightly:nightly-20240816-01
    restart: unless-stopped
    environment:
      TOKEN_COOKIE_NAME: ${TOKEN_COOKIE_NAME:-linkstash-token}
      BACKEND_URL: ${BACKEND_URL:-http://localhost}:${BACKEND_PORT:-3030}
    ports:
      - ${FRONTEND_PORT:-3000}:3000
    depends_on:
      - linkstash-backend
volumes:
  linkstash-data:
