name: Build and Push Docker Image on Tag

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      tag_name:
        description: "Simulated tag name for testing"
        required: false

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project:
          - linkstash-backend
          - linkstash-frontend

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Extract Docker tag and validate
    - name: Extract Docker tag
      id: extract-tag
      run: |
        TAG_NAME=${{ github.event.inputs.tag_name || github.ref_name }}
        if [[ $TAG_NAME =~ ^(.+)_v([0-9]+\.[0-9]+)$ ]]; then
          PROJECT_NAME="${BASH_REMATCH[1]}"
          VERSION="${BASH_REMATCH[2]}"
          echo "PROJECT_NAME=${PROJECT_NAME}" >> $GITHUB_ENV
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo "VALID_TAG=true" >> $GITHUB_ENV
        else
          echo "VALID_TAG=false" >> $GITHUB_ENV
        fi

    # Step 3: Skip unrelated or invalid tags
    - name: Check tag validity and project match
      if: ${{ env.VALID_TAG == 'false' || env.PROJECT_NAME != matrix.project }}
      run: |
        echo "Skipping job. Either tag is invalid or does not match the project: ${{ matrix.project }}"
        exit 0

    # Step 4: Log in to DockerHub
    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 5: Build the Docker image
    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ matrix.project }}:${{ env.VERSION }} ./${{ matrix.project }}

    # Step 6: Push the Docker image
    - name: Push Docker image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/${{ matrix.project }}:${{ env.VERSION }}
